### ISSUE TITLE
Repository makeover

### ISSUE THREAD

**Issue by HagenFritz** [intelligent-environments-lab/bleed-orange-measure-purple#13]
# Formalizing the Repository
Perhaps there is a benefit t0 revamping the layout of the repository to correspond more closely with that given by [cookie cutter data science](https://drivendata.github.io/cookiecutter-data-science/).

## Problem 
Well the layout might look and function nicely for us and others looking at our project, there would be a lot of code references that would need fixing.

## Solution
There are three options:
1. Remake the repository in accordance with [cookie cutter data science](https://drivendata.github.io/cookiecutter-data-science/)
2. Create a new repository and slowly move over files, scripts, etc. to the no project
3. Do nothing -> always a viable option

**Comment by calvinjlin** [comment]
Started on branch [project-restructure](https://github.com/intelligent-environments-lab/bleed-orange-measure-purple/tree/project-restructure). Files have been relocated, but code references have yet to be corrected. 

Mainly, there is a need to decide on the current working directory so that script dependencies work properly and figure out how to direct a script to the data folder
- Using [pathlib to go up directories](https://stackoverflow.com/questions/27844088/python-get-directory-two-levels-up) or creating a [.env file](https://pypi.org/project/python-dotenv/) may help.
- The current working directory can be easily defined in Spyder, but what if the user is using another IDE.
- If CWD is specified under the repo's root folder, import references would have to start with import src. On the other hand, placing the CWD under the src folder would solve this problem, but it would make it harder to access the data folder which is in the repo's root folder.

**Comment by calvinjlin** [comment]
Overall, transition to the new structure is complete for the most part.
