### ISSUE TITLE
Validation of A data using B data

### ISSUE THREAD

**Issue by calvinjlin** [intelligent-environments-lab/bleed-orange-measure-purple#37]
# Channel Reliability
Currently we are using Channel A data only, but this data might be unreliable so we should compare this data to Channel B and use both channels if we can or the better of the two.

Some ways we might do this:
- **Historic Data**: Looking at some of the figures online, there are sensors that periodically _spike to ungodly levels_. These should be easy to identify and therefore exclude these channels. We can also see if the sensors start reading _negative_ (is this possible?) or _zero_ for extended periods of time. 
- **Measurement Difference in A and B**: We can also look at the delta between channels A and B and if there is a sizeable gap, we can compare the channel readings to nearby PAs to see which channel on the original PA is more consistent. 
- **Other Sources**: In a pdf produced by the EPA, it describes a method for utilizing the two A/B channels to validate each other: [PurpleAir PM 2 5 US Correction and Performance ... - EPA](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwigtq-a28rrAhUFY6wKHfdRDeEQFjAAegQIAhAB&url=https%3A%2F%2Fcfpub.epa.gov%2Fsi%2Fsi_public_file_download.cfm%3Fp_download_id%3D539905%26Lab%3DCEMM&usg=AOvVaw1sX-dsXT2VivOcnnUPO_GI)

**Comment by HagenFritz** [comment]
# Update
As per our meeting on 09/09, a few minor updates.

## Comparison Interval
We want to compare the values from A and B or a short interval, but not too short to ensure we have a good overlap on measured values. The suspected optimal interval would be **10 minutes** which should guarantee at least 4 data points within the same time window.

## Automatic vs Manual
There are some patterns that can be be easily determined by coding them in (see **Historic Data** in the original issue post) while others might need to be manually identified (see **Measurement Difference in A and B**). The important thing is that we _identify_ there is an issue. If we can determine which channel is problematic in the code, then we should do that. Otherwise, we should just flag the issue and figure it out manually.

**Comment by HagenFritz** [comment]
Plot generated and data removed that don't fit
